---
- name: "Configure Watcher"
  hosts: all
  become: true

  tasks:
    - name: "Update cache"
      ansible.builtin.dnf:
        update_cache: true

    - name: "install EPEL"
      ansible.builtin.dnf:
        name: epel-release
        state: present

    - name: "install packages"
      ansible.builtin.dnf:
        name:
          - curl
          - nmap
          - iputils
          - prometheus
          - rsyslog
        state: present
