---
- name: "Configure Watcher"
  hosts: all
  become: true

  handlers:
    - name: restart_rsyslog
      ansible.builtin.service:
        name: rsyslog
        state: restarted

  tasks:
    - name: Set timezone to Brasilia
      community.general.timezone:
        name: America/Sao_Paulo
    - name: "Update cache"
      ansible.builtin.dnf:
        update_cache: true

    - name: "install EPEL"
      ansible.builtin.dnf:
        name: epel-release
        state: present

    - name: "install packages"
      ansible.builtin.dnf:
        name:
          - curl
          - nmap
          - iputils
          - prometheus
          - rsyslog
          - firewalld
          - python3-firewall
        state: present

    - name: copy rsyslog server config
      ansible.builtin.copy:
        dest: /etc/rsyslog.d/10-remote-server.conf
        src: files/config/rsyslog-server.conf
        owner: root
        group: root
        mode: 0644
      notify: restart_rsyslog
    - name: Ensure rsyslog is running
      ansible.builtin.systemd_service:
        name: rsyslog
        state: started
        enabled: true

    - name: Ensure firewalld is running
      ansible.builtin.service:
        name: firewalld
        state: started
        enabled: true
    - name: Allow rsyslog TCP port
      ansible.posix.firewalld:
        port: 514/tcp
        permanent: true
        immediate: true
        state: enabled
    - name: Apply pending handlers
      ansible.builtin.meta: flush_handlers
