Vagrant.configure("2") do |config|

  config.vm.define "web" do |web|
    web.vm.box = "almalinux/9"
    web.vm.hostname = "web"
    web.vm.network "private_network",
      ip: "192.168.56.10"
    web.vm.provider "libvirt" do |libvirt|
      libvirt.memory = 1024
      libvirt.cpus = 1
    end

    web.vm.provision "ansible" do |ansible|
      ansible.playbook = "ansible/server.yml"
    end
  end
  config.vm.define "client" do |client|
    client.vm.box = "almalinux/9"
    client.vm.hostname = "client"
    client.vm.network "private_network",
      ip: "192.168.56.20"
    client.vm.provider "libvirt" do |libvirt|
      libvirt.memory = 1024
      libvirt.cpus = 1
    end

    # client.vm.provision "ansible" do |ansible|
    #   ansible.playbook = "ansible/client.yml"
    # end
  end

end