
Vagrant.configure("2") do |config|

  config.vm.define "watcher" do |watcher|
    watcher.vm.box = "almalinux/9"
    watcher.vm.hostname = "watcher"
    watcher.vm.network "private_network",
      ip: "192.168.56.10"
    watcher.vm.provider "libvirt" do |libvirt|
      libvirt.memory = 4096
      libvirt.cpus = 1
    end

    watcher.vm.provision "ansible" do |ansible|
      ansible.playbook = "ansible/watcher.yml"
    end
  end
  config.vm.define "server" do |server|
    server.vm.box = "almalinux/9"
    server.vm.hostname = "server"
    server.vm.network "private_network",
      ip: "192.168.56.20"
    server.vm.provider "libvirt" do |libvirt|
      libvirt.memory = 4096
      libvirt.cpus = 1
    end

    server.vm.provision "ansible" do |ansible|
      ansible.playbook = "ansible/server.yml"
    end
  end
  config.vm.define "client" do |client|
    client.vm.box = "almalinux/9"
    client.vm.hostname = "client"
    client.vm.network "private_network",
      ip: "192.168.56.30"
    client.vm.provider "libvirt" do |libvirt|
      libvirt.memory = 4096
      libvirt.cpus = 1
    end
    client.vm.provision "ansible" do |ansible|
      ansible.playbook = "ansible/client.yml"
    end
  end


end
