module(load="imtcp")

template(
name="RemotePerHost"
type="string"
string="/var/log/remote/%HOSTNAME:::secpath-replace%/messages.log"
)

ruleset(name="remote") {
action(
  type="omfile"
  dynaFile="RemotePerHost"
  createDirs="on"
)
}

input(
type="imtcp"
port="514"
ruleset="remote"
)